import type { Metadata } from "next";
import { montserratNormal } from "@/components/ui/fonts";
import Footer from "@/components/layout/footer";
import "../../globals.css";
import Navbar from "@/components/layout/navbar";

export const metadata: Metadata = {
    title: "BlackCat Media",
    description: "Generated by create next app",
};

export default function BlogsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${montserratNormal.className} antialiased`}
            >
                <div className="relative w-full h-screen">
                    {/* Header */}
                    <Navbar imagePath="/images/blackCat-black.png" />

                    {/* Main content */}
                    <main>
                        {children}

                        <Footer />
                    </main>
                </div>
            </body>
        </html>
    );
}
