import type { Metadata } from "next";
import { montserratNormal } from "@/components/ui/fonts";
import Footer from "@/components/layout/footer";
import "../globals.css";
import Navbar from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "BlackCat Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratNormal.className} antialiased`}
      >
        <Navbar imagePath="./blackcat-logo.svg" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
