import type { Metadata } from "next";
import { montserratNormal } from "@/components/ui/fonts";
import Footer from "@/components/layout/footer";
import "../globals.css";
import Navbar from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "BlackCat Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratNormal.className} antialiased`}>
        <div className="relative flex min-h-screen flex-col">
          <Navbar variant="dark" />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
